/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkflowEditorRouteImport } from './routes/workflow-editor'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebookIndexRouteImport } from './routes/notebook/index'
import { Route as DomainDomainIdRouteImport } from './routes/domain/$domainId'
import { Route as SubjectDomainIdSubjectIdRouteImport } from './routes/subject/$domainId/$subjectId'
import { Route as NotebookDomainIdSubjectIdRouteImport } from './routes/notebook/$domainId/$subjectId'
import { Route as ChapterDomainIdSubjectIdChapterIdRouteImport } from './routes/chapter/$domainId/$subjectId/$chapterId'
import { Route as TopicDomainIdSubjectIdChapterIdTopicIdRouteImport } from './routes/topic/$domainId/$subjectId/$chapterId/$topicId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowEditorRoute = WorkflowEditorRouteImport.update({
  id: '/workflow-editor',
  path: '/workflow-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIndexRoute = NotebookIndexRouteImport.update({
  id: '/notebook/',
  path: '/notebook/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainDomainIdRoute = DomainDomainIdRouteImport.update({
  id: '/domain/$domainId',
  path: '/domain/$domainId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectDomainIdSubjectIdRoute =
  SubjectDomainIdSubjectIdRouteImport.update({
    id: '/subject/$domainId/$subjectId',
    path: '/subject/$domainId/$subjectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const NotebookDomainIdSubjectIdRoute =
  NotebookDomainIdSubjectIdRouteImport.update({
    id: '/notebook/$domainId/$subjectId',
    path: '/notebook/$domainId/$subjectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChapterDomainIdSubjectIdChapterIdRoute =
  ChapterDomainIdSubjectIdChapterIdRouteImport.update({
    id: '/chapter/$domainId/$subjectId/$chapterId',
    path: '/chapter/$domainId/$subjectId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TopicDomainIdSubjectIdChapterIdTopicIdRoute =
  TopicDomainIdSubjectIdChapterIdTopicIdRouteImport.update({
    id: '/topic/$domainId/$subjectId/$chapterId/$topicId',
    path: '/topic/$domainId/$subjectId/$chapterId/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/graph': typeof GraphRoute
  '/workflow-editor': typeof WorkflowEditorRoute
  '/workflows': typeof WorkflowsRoute
  '/domain/$domainId': typeof DomainDomainIdRoute
  '/notebook/': typeof NotebookIndexRoute
  '/notebook/$domainId/$subjectId': typeof NotebookDomainIdSubjectIdRoute
  '/subject/$domainId/$subjectId': typeof SubjectDomainIdSubjectIdRoute
  '/chapter/$domainId/$subjectId/$chapterId': typeof ChapterDomainIdSubjectIdChapterIdRoute
  '/topic/$domainId/$subjectId/$chapterId/$topicId': typeof TopicDomainIdSubjectIdChapterIdTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/graph': typeof GraphRoute
  '/workflow-editor': typeof WorkflowEditorRoute
  '/workflows': typeof WorkflowsRoute
  '/domain/$domainId': typeof DomainDomainIdRoute
  '/notebook': typeof NotebookIndexRoute
  '/notebook/$domainId/$subjectId': typeof NotebookDomainIdSubjectIdRoute
  '/subject/$domainId/$subjectId': typeof SubjectDomainIdSubjectIdRoute
  '/chapter/$domainId/$subjectId/$chapterId': typeof ChapterDomainIdSubjectIdChapterIdRoute
  '/topic/$domainId/$subjectId/$chapterId/$topicId': typeof TopicDomainIdSubjectIdChapterIdTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/graph': typeof GraphRoute
  '/workflow-editor': typeof WorkflowEditorRoute
  '/workflows': typeof WorkflowsRoute
  '/domain/$domainId': typeof DomainDomainIdRoute
  '/notebook/': typeof NotebookIndexRoute
  '/notebook/$domainId/$subjectId': typeof NotebookDomainIdSubjectIdRoute
  '/subject/$domainId/$subjectId': typeof SubjectDomainIdSubjectIdRoute
  '/chapter/$domainId/$subjectId/$chapterId': typeof ChapterDomainIdSubjectIdChapterIdRoute
  '/topic/$domainId/$subjectId/$chapterId/$topicId': typeof TopicDomainIdSubjectIdChapterIdTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/graph'
    | '/workflow-editor'
    | '/workflows'
    | '/domain/$domainId'
    | '/notebook/'
    | '/notebook/$domainId/$subjectId'
    | '/subject/$domainId/$subjectId'
    | '/chapter/$domainId/$subjectId/$chapterId'
    | '/topic/$domainId/$subjectId/$chapterId/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/graph'
    | '/workflow-editor'
    | '/workflows'
    | '/domain/$domainId'
    | '/notebook'
    | '/notebook/$domainId/$subjectId'
    | '/subject/$domainId/$subjectId'
    | '/chapter/$domainId/$subjectId/$chapterId'
    | '/topic/$domainId/$subjectId/$chapterId/$topicId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/graph'
    | '/workflow-editor'
    | '/workflows'
    | '/domain/$domainId'
    | '/notebook/'
    | '/notebook/$domainId/$subjectId'
    | '/subject/$domainId/$subjectId'
    | '/chapter/$domainId/$subjectId/$chapterId'
    | '/topic/$domainId/$subjectId/$chapterId/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  GraphRoute: typeof GraphRoute
  WorkflowEditorRoute: typeof WorkflowEditorRoute
  WorkflowsRoute: typeof WorkflowsRoute
  DomainDomainIdRoute: typeof DomainDomainIdRoute
  NotebookIndexRoute: typeof NotebookIndexRoute
  NotebookDomainIdSubjectIdRoute: typeof NotebookDomainIdSubjectIdRoute
  SubjectDomainIdSubjectIdRoute: typeof SubjectDomainIdSubjectIdRoute
  ChapterDomainIdSubjectIdChapterIdRoute: typeof ChapterDomainIdSubjectIdChapterIdRoute
  TopicDomainIdSubjectIdChapterIdTopicIdRoute: typeof TopicDomainIdSubjectIdChapterIdTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-editor': {
      id: '/workflow-editor'
      path: '/workflow-editor'
      fullPath: '/workflow-editor'
      preLoaderRoute: typeof WorkflowEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/': {
      id: '/notebook/'
      path: '/notebook'
      fullPath: '/notebook/'
      preLoaderRoute: typeof NotebookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$domainId': {
      id: '/domain/$domainId'
      path: '/domain/$domainId'
      fullPath: '/domain/$domainId'
      preLoaderRoute: typeof DomainDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$domainId/$subjectId': {
      id: '/subject/$domainId/$subjectId'
      path: '/subject/$domainId/$subjectId'
      fullPath: '/subject/$domainId/$subjectId'
      preLoaderRoute: typeof SubjectDomainIdSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$domainId/$subjectId': {
      id: '/notebook/$domainId/$subjectId'
      path: '/notebook/$domainId/$subjectId'
      fullPath: '/notebook/$domainId/$subjectId'
      preLoaderRoute: typeof NotebookDomainIdSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$domainId/$subjectId/$chapterId': {
      id: '/chapter/$domainId/$subjectId/$chapterId'
      path: '/chapter/$domainId/$subjectId/$chapterId'
      fullPath: '/chapter/$domainId/$subjectId/$chapterId'
      preLoaderRoute: typeof ChapterDomainIdSubjectIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$domainId/$subjectId/$chapterId/$topicId': {
      id: '/topic/$domainId/$subjectId/$chapterId/$topicId'
      path: '/topic/$domainId/$subjectId/$chapterId/$topicId'
      fullPath: '/topic/$domainId/$subjectId/$chapterId/$topicId'
      preLoaderRoute: typeof TopicDomainIdSubjectIdChapterIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  GraphRoute: GraphRoute,
  WorkflowEditorRoute: WorkflowEditorRoute,
  WorkflowsRoute: WorkflowsRoute,
  DomainDomainIdRoute: DomainDomainIdRoute,
  NotebookIndexRoute: NotebookIndexRoute,
  NotebookDomainIdSubjectIdRoute: NotebookDomainIdSubjectIdRoute,
  SubjectDomainIdSubjectIdRoute: SubjectDomainIdSubjectIdRoute,
  ChapterDomainIdSubjectIdChapterIdRoute:
    ChapterDomainIdSubjectIdChapterIdRoute,
  TopicDomainIdSubjectIdChapterIdTopicIdRoute:
    TopicDomainIdSubjectIdChapterIdTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
